/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motelinteligente.telas;


import com.motelinteligente.dados.MiniCalendario;
import com.motelinteligente.dados.fazconexao;
import com.motelinteligente.dados.fprodutos;
import com.motelinteligente.dados.vendaProdutos;
import java.beans.PropertyChangeEvent;
import java.sql.Connection;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import com.motelinteligente.pdf.Relatorio;
import com.motelinteligente.pdf.RelatorioProdutosPDF;

/**
 *
 * @author MOTEL
 */
public class ConferenciaProdutos extends javax.swing.JFrame {

    String data1 = null, data2 = null;

    /**
     * Creates new form ConferenciaCaixa
     */
    public ConferenciaProdutos() {
        initComponents();
        SpinnerModel spinnerHabre = new SpinnerNumberModel(0, 0, 23, 1);
        SpinnerModel spinnerHabre1 = new SpinnerNumberModel(0, 0, 23, 1);
        SpinnerModel spinnerHfecha = new SpinnerNumberModel(0, 0, 23, 1);
        SpinnerModel spinnerHfecha1 = new SpinnerNumberModel(0, 0, 23, 1);
        SpinnerModel spinnerMabre1 = new SpinnerNumberModel(0, 0, 59, 1);
        SpinnerModel spinnerMabre = new SpinnerNumberModel(0, 0, 59, 1);
        SpinnerModel spinnerMfecha = new SpinnerNumberModel(0, 0, 59, 1);
        SpinnerModel spinnerMfecha1 = new SpinnerNumberModel(0, 0, 59, 1);
        horaAb.setModel(spinnerHabre);
        horaAb1.setModel(spinnerHabre1);
        minAb.setModel(spinnerMabre1);
        minAb1.setModel(spinnerMabre);
        tabela.setRowHeight(30);
        tabela.getColumn(tabela.getColumnName(0)).setPreferredWidth(100);
        tabela.getColumn(tabela.getColumnName(1)).setPreferredWidth(200);
        tabela.getColumn(tabela.getColumnName(2)).setPreferredWidth(100);
        tabela.getColumn(tabela.getColumnName(3)).setPreferredWidth(200);
        tabela.getColumn(tabela.getColumnName(4)).setPreferredWidth(200);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minAb2 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        horaAb2 = new javax.swing.JSpinner();
        lbltotalprodutosvendidos = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblquantidadevendida = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        aberto1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        aberto2 = new javax.swing.JTextField();
        btgerar = new javax.swing.JButton();
        horaAb = new javax.swing.JSpinner();
        minAb = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        minAb1 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        horaAb1 = new javax.swing.JSpinner();
        carregaDados = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lbltotalprodutosvendidos1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblquantidadevendida1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel10.setText("min");

        jLabel11.setText("h");

        lbltotalprodutosvendidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltotalprodutosvendidos.setText("jLabel16");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Valor Total:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Produtos Vendidos");

        lblquantidadevendida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblquantidadevendida.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Vendidos de:");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Relatório de Produtos Vendidos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 345, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        aberto1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        aberto1.setText("   /     /  ");
        aberto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aberto1MouseClicked(evt);
            }
        });
        aberto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aberto1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("até");

        aberto2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        aberto2.setText("   /     /  ");
        aberto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aberto2MouseClicked(evt);
            }
        });

        btgerar.setText("GERAR");
        btgerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgerarActionPerformed(evt);
            }
        });

        jLabel6.setText("h");

        jLabel7.setText("min");

        jLabel8.setText("min");

        jLabel9.setText("h");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(horaAb, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minAb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(aberto1))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(horaAb1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minAb1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addComponent(aberto2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116)
                .addComponent(btgerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horaAb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minAb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aberto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aberto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(horaAb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(minAb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btgerar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(66, 66, 66))
        );

        tabela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Descrição", "Quantidade", "Valor Unidade", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabela.setPreferredSize(new java.awt.Dimension(850, 80));
        jScrollPane1.setViewportView(tabela);

        lbltotalprodutosvendidos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltotalprodutosvendidos1.setText("0");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Valor Total:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Produtos Vendidos");

        lblquantidadevendida1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblquantidadevendida1.setText("0");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pdf_icon.png"))); // NOI18N
        jButton1.setText("Gerar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        carregaDados.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        carregaDados.setLayer(lbltotalprodutosvendidos1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        carregaDados.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        carregaDados.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        carregaDados.setLayer(lblquantidadevendida1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        carregaDados.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout carregaDadosLayout = new javax.swing.GroupLayout(carregaDados);
        carregaDados.setLayout(carregaDadosLayout);
        carregaDadosLayout.setHorizontalGroup(
            carregaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carregaDadosLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(carregaDadosLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblquantidadevendida1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(53, 53, 53)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltotalprodutosvendidos1)
                .addGap(66, 66, 66))
        );
        carregaDadosLayout.setVerticalGroup(
            carregaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carregaDadosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(carregaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carregaDadosLayout.createSequentialGroup()
                        .addGroup(carregaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(lblquantidadevendida1)
                            .addComponent(lbltotalprodutosvendidos1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carregaDadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carregaDados)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carregaDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void carregaTabela(ArrayList<Integer> idList) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setNumRows(0);
        vendaProdutos venda = new vendaProdutos();
        vendaProdutos.gerenciaVenda gerenciaVenda = venda.new gerenciaVenda();
        List<vendaProdutos> vendas = gerenciaVenda.listaPorLocacao(idList);
        int quantidadeVendida = 0;
        float valorVendido = 0;
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        //JScrollPane scrollPane = new JScrollPane(tabelaProdutos);
        for (vendaProdutos v : vendas) {
            String desc = new fprodutos().getDescicao(String.valueOf(v.idProduto));
            modelo.addRow(new Object[]{
                v.idProduto,
                desc,
                v.quantidade,
                v.valorUnd,
                v.quantidade * v.valorUnd
            });
            quantidadeVendida += v.quantidade;
            valorVendido += (v.quantidade * v.valorUnd);
        }

        lbltotalprodutosvendidos1.setText("R$" + String.valueOf(valorVendido));
        lblquantidadevendida1.setText(String.valueOf(quantidadeVendida));

    }


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btgerar.grabFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btgerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgerarActionPerformed
        // pegar os textos dos campos
        tabela.setVisible(true);
        ArrayList<Integer> idList = new ArrayList<>();

        String dataAbre1 = null;
        String dataAbre2 = null;
        String horaA1, horaA2, horaF1, horaF2;
        String minA1, minA2, minF1, minF2;
        try {
            if (!"   /     /  ".equals(aberto1.getText())) {
                dataAbre1 = aberto1.getText();
                horaA1 = String.format("%02d", (int) horaAb.getValue());
                minA1 = String.format("%02d", (int) minAb.getValue());
                dataAbre1 = dataAbre1 + " " + horaA1 + ":" + minA1;

            } else {
                dataAbre1 = null;
            }
            if (!"   /     /  ".equals(aberto2.getText())) {
                dataAbre2 = aberto2.getText();
                horaA2 = String.format("%02d", (int) horaAb1.getValue());
                minA2 = String.format("%02d", (int) minAb1.getValue());
                dataAbre2 = dataAbre2 + " " + horaA2 + ":" + minA2;

            } else {
                dataAbre2 = null;
            }

            String consultaSQL = "SELECT idlocacao FROM registralocado WHERE 1=1";

            // Verifique e adicione cláusulas WHERE conforme as datas fornecidas pelo usuário
            if (dataAbre1 != null) {
                consultaSQL += " AND horafim >= ?";
            }
            if (dataAbre2 != null) {
                consultaSQL += " AND horafim <= ?";
            }
            java.sql.Connection link = new fazconexao().conectar();
            PreparedStatement stmt = link.prepareStatement(consultaSQL);
            int index = 1;

            if (dataAbre1 != null) {
                stmt.setString(index, dataAbre1);
                index++;
            }
            if (dataAbre2 != null) {
                stmt.setString(index, dataAbre2);
                index++;
            }

            ResultSet resultSet = stmt.executeQuery();

            while (resultSet.next()) {
                int id = resultSet.getInt("idlocacao");
                idList.add(id);
            }

            // chama a funcao para carregar a tabela
            carregaTabela(idList);
            data1 = dataAbre1;
            data2 = dataAbre2;
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btgerarActionPerformed

    private void aberto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aberto2MouseClicked
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        MiniCalendario miniCalendario = new MiniCalendario();

        miniCalendario.addPropertyChangeListener((PropertyChangeEvent evt1) -> {
            String novaData = (String) evt1.getNewValue();
            aberto2.setText(novaData);
        });
        miniCalendario.MiniCalendario(x, y);
    }//GEN-LAST:event_aberto2MouseClicked

    private void aberto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aberto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aberto1ActionPerformed

    private void aberto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aberto1MouseClicked
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        MiniCalendario miniCalendario = new MiniCalendario();

        miniCalendario.addPropertyChangeListener((PropertyChangeEvent evt1) -> {
            String novaData = (String) evt1.getNewValue();
            aberto1.setText(novaData);
        });
        miniCalendario.MiniCalendario(x, y);
    }//GEN-LAST:event_aberto1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // prepara para gerar pdf
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        if (model.getRowCount() > 0) {
            prepararPDF();
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum dado na tabela.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void prepararPDF() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        String dataPasssar = "Produtos vendidos ";
        if(data1 != null){
            dataPasssar+= " de " + data1;
        }
        if(data2 != null){
            dataPasssar+= " até " + data2;
        }
        
        List<List<Object>> dadosDasColunas = new ArrayList<>();

        for (int i = 0; i < model.getRowCount(); i++) {
            List<Object> dadosLinha = new ArrayList<>();

            Object dadoColuna1 = model.getValueAt(i, 0); // 2ª coluna
            Object dadoColuna2 = model.getValueAt(i, 1); // 2ª coluna
            Object dadoColuna3 = model.getValueAt(i, 2); // 3ª coluna
            Object dadoColuna4 = model.getValueAt(i, 3); // 4ª coluna
            Object dadoColuna5 = model.getValueAt(i, 4); // 5ª coluna

            // Adiciona os dados da linha à lista
            dadosLinha.add(dadoColuna1);
            dadosLinha.add(dadoColuna2);
            dadosLinha.add(dadoColuna3);
            dadosLinha.add(dadoColuna4);
            dadosLinha.add(dadoColuna5);

            // Adiciona os dados da linha à lista principal
            dadosDasColunas.add(dadosLinha);
        }

        Relatorio relatorioPdfSimples = new RelatorioProdutosPDF();
        relatorioPdfSimples.gerarCabecalho(dataPasssar);
        relatorioPdfSimples.gerarCorpo(dadosDasColunas);
        relatorioPdfSimples.gerarRodape();
        relatorioPdfSimples.imprimir();
    }

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConferenciaProdutos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConferenciaProdutos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConferenciaProdutos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConferenciaProdutos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConferenciaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aberto1;
    private javax.swing.JTextField aberto2;
    private javax.swing.JButton btgerar;
    private javax.swing.JDesktopPane carregaDados;
    private javax.swing.JSpinner horaAb;
    private javax.swing.JSpinner horaAb1;
    private javax.swing.JSpinner horaAb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblquantidadevendida;
    private javax.swing.JLabel lblquantidadevendida1;
    private javax.swing.JLabel lbltotalprodutosvendidos;
    private javax.swing.JLabel lbltotalprodutosvendidos1;
    private javax.swing.JSpinner minAb;
    private javax.swing.JSpinner minAb1;
    private javax.swing.JSpinner minAb2;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
